# Generated by Django 4.0.3 on 2022-03-09 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rating_review_albumn'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Albumn',
            new_name='Album',
        ),
    ]
