# Generated by Django 4.0.3 on 2022-03-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_albumn_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='songs',
            field=models.JSONField(default=list),
        ),
    ]
