# Generated by Django 4.0.3 on 2022-03-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_album_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.JSONField(default=list),
        ),
    ]
