# Generated by Django 4.0.3 on 2022-03-09 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='review',
            field=models.CharField(default=str, max_length=1000),
        ),
        migrations.CreateModel(
            name='Albumn',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('songs', models.JSONField(default=list)),
                ('releaseDate', models.DateField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.artist')),
            ],
        ),
    ]
