# Generated by Django 4.0.3 on 2022-03-10 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_album_songs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='songs',
        ),
    ]
