# Generated by Django 4.0.4 on 2022-04-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_album_songs_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='songs',
            field=models.JSONField(default=list),
        ),
    ]
