# Generated by Django 4.0.4 on 2022-04-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_album_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='songs',
            field=models.JSONField(default=list),
        ),
    ]
